### PR TITLE
Make open method raise only IOError exception. Bump minio-py version to 2.2.4

### PR DESCRIPTION
**Pull request by Yurmusp**
Make open method throw only IOError exception. 
Bump minio-py version to 2.2.4

### CODE REVIEW

**Comment by Yurmusp** [comment]
Hi @thomasf,

 This pull request does what is in its title.
I did open() call to throw only IOError because of number of reasons.
a) All other methods do exactly that
b) S3 Bota Storage implementation also does it this way.
c) In my opinion Storage interface is defined by Django and our implementation of it shall not contain anything outside of django definition and standard Python things. Exceptions that are thrown are actually part of interface. On exception side it means it shall throw only IOError and ValueError. Can be some other standard python errors, but it seems no other storage does it and I do not see reasons why we shall do it. All other minio-py exceptions shall not propagate beyond Storage interface and shall be repacked or consumed inside.
I bumped version of minio-py. With older version my project fails and I waited for this 2.2.4 version because of that.

Please, review. Let's discuss and approve. 
Thank you.

**Comment by thomasf** [comment]
As I previosly stated I think that `NoSuchBucket` should remain as it is an
indication of an configuration error rather than something to handle at run
time. It should fail as hard as possible as soon as possible.

This also applies to `InvalidEncryptionAlgorithmError`, `AccountProblem`,
`CredentialNotSupported`, `CrossLocationLoggingProhibited`, `ExpiredToken`,
`InvalidAccessKeyId` , `InvalidBucketName`, `InvalidSecurity`, maybe
`AccessDenied` and possibly other errors which would not happen if the user
confiuguration is correctly set up.
 
The following code is problematic since it makes it hard to handle errors
properly in python code if they only difference between the errors are the
string content:

```py
raise IOError("File {} could not be saved".format(name) + ' ' + str(error))
```

I would also prefer if the errors were wrapped individually in their own
classes so that they can be matched by `except` statements. Probably by
creating an errors.py and redefine all exception classes there.


Not letting misconfiguration exceptions slip trough plus having a single string
IOError class also hides a lot of useful information for log/exception
monitoring solutions. When you define monitoring alerts or use dashboards like
grafana you usually just counts the number of exception types over a whole
custer of web servers and to be able to see what's actually going on without
having to start digging throug the logs can be very useful for quickly
understanding why your application fails.

**Comment by Yurmusp** [comment]
Hi @thomasf ,

I see it the following way.
Since two of most used  implementations (I mean FileSystemStorage and Amazon Bota's S3Storage) mostly throw single type exception, I think we shall be compatible.
I can see that we can achieve it by just inheriting from IOError and create extra individual exceptions as part of our interface for MinioStorage. This way we achieve what you want and still remain compatible with others the way I want.
I think it is wrong to use minio-py exceptions. We either fully hide them or fully repack and publish as part of our MinioStorage interface.
This is kind of more complete way of doing things that satisfies both sides.
However, it is more work.

Let me know if you are OK with this approach.

**Comment by thomasf** [comment]
Yes, that was what I wanted to suggest.

The minio-py `ResponseError` also contains lots of metadata which we should
preserve for user error handling. We can probably create our own proxy
Exception base class which inherits from `IOError` and embeds the underlying
`MinioError`'s

We can probably also create another proxy exception base class which inherits
from `django.core.exceptions.ImproperlyConfigured` for many of the exceptions I
listed before.

Btw, it's obvious that `FileSystemStorage` should raise those exceptions
because it's actual files which is all good. It's not at all clear how remote
storage systems should behave, if it was the Django developers would have
documented exception types as part of the APIs.

**Comment by Yurmusp** [comment]
I looked at S3 Bota impl and they just wrap everything into exception
inherited from IOError/OSError.

FileSystemStorage throws IOError and bypasses anything coming from file
operations with some outliers
where he wants to return some bool value.

**Comment by thomasf** [comment]
I think this might be ok https://github.com/py-pa/django-minio-storage/pull/40/files

It just need a function which decided if an exception is to be wrapped or not so that configuration errors can be raised unmodified in a easy way.,

**Pull request closed without merging**
