### PR TITLE
Made it works with python2.7

### PR DESCRIPTION
**Pull request by yml**
super() in python 3 is equivalent to super(klass, self) in python 2.7

### CODE REVIEW

**Comment by yml** [comment]
I have also removed some non ascii char from the docstrings.

**Comment by tomhoule** [comment]
Thanks for the PR, I'll take time to look into it over the week-end and come back to you.

Tangentially, if we are going to support multiple versions, I think we should automate testing with all supported versions (via Travis/Tox).

Also please note that although I have been testing it with a project of mine currently in development, I don’t think the library is tested enough to be used in production yet. I’ll get in touch with the minio developers soon to ask their opinion on the library.

**Comment by tomhoule** [comment]
Sorry for the delay. I'm going to merge.

I contacted the minio devs and it turns out there is another library that does the same as this one, by @shapoglyk. We discussed it and we are going to join the efforts on a common repo. So I'm going to work on making it production-ready.

As for testing, I looked into dockerized travis builds and it seems it would be pretty easy to test on both python 2.7 and the latest.

**Comment by yml** [comment]
Thank you for creating this backend and working toward making it production ready. I tried the other library  but I had no luck with it. I have not spent a ton of time debuguing the issue but for some reason uploading a Media file was entering into an "infinite" loop. 

Having a good test suite run on multiple python and django versions would be amazing.

**Pull request merged**
