### PR TITLE
Fix for file exists check, improved builds, refactors and improves tests

### PR DESCRIPTION
**Pull request by fazpu**
This PR is still in progress due to changes in the travis ci build. 

Important changes are:
* The travis with tox setup was inspired by django rest framework.
* The mock tests were removed - they were failing and I also believe the test logic was not actually testing anything. Please correct me if I am wrong.
* new integration tests written
* Error concerning file retrieval was corrected
* It is now possible to return public (non-presigned) URIs
* It is now possible to return partial URIs. This was necessary due to bad URI formats when deployed in Docker clusters.

### CODE REVIEW

**Comment by fazpu** [comment]
The PR is ready.

**Comment by tomhoule** [comment]
Thanks a lot for your work! I'm unfortunately very busy these days and it took me way too long to get around to reading your PR, I'm sorry for that.

I have no objection to the contents, it's really great that you could implement testing on tox. It's merged :)

As motivated by [this post](http://felixge.de/2013/03/11/the-pull-request-hack.html), and in case you want to make changes in the future, I will give you commit rights on this repo.

**Comment by thomasf** [comment]
the Dockerfile still has run_tests.sh as the default command and the python:3.5 entrypoint seems to otherwise be the the python interpreter.. 

Maybe the docker-compose file or at least the django service isnt needed anymore?

**Comment by thomasf** [comment]
The minio in docker-compose.yml also doesnt have the same password as the one in the travis setup..
detox also fails to run tests in parallel since all tests in the matrix runs against the same minio instance, ~maybe a separate port per environment?~, maybe a bucket prefix could be generated for each toxenv instead?

**Comment by thomasf** [comment]
Ive made the changes I suggested in #15

**Pull request merged**
