### PR TITLE
Add limit url time

### PR DESCRIPTION
**Pull request by Sunnnner**

### CODE REVIEW

**Comment by thomasf** [comment]
Don't repeat the code.. Maybe something like this instead:

```py
kwargs={}
if expires is not None: 
   kwargs['expires']=expires

...
url = self.client.presigned_get_object(self.bucket_name, name, **kwargs)
```

**Comment by thomasf** [comment]
If possible I would like a test which shows that an url actually have expired or actually works, maybe mock/override whatever `datetime.now()` or similar method minio client uses to create an already invalid url. It's not super important but it would alert us if the minio python library silently changes it's behavior.

**Comment by thomasf** [comment]
Maybe a presigned url should always be returned if expires arguments are used..

```py
if self.presign_urls or expires is not None:
    ....
```
It's not good if the function accepts an expires value and then not returning an URL which actually does expire. I rather see that an exception is rasied rather than returning a non expiring URL.

**Comment by Sunnnner** [comment]
> Maybe a presigned url should always be returned if expires arguments are used..
> 
> ```python
> if self.presign_urls or expires is not None:
>     ....
> ```
> 
> It's not good if the function accepts an expires value and then not returning an URL which actually does expire. I rather see that an exception is rasied rather than returning a non expiring URL.

> I'm careless, this code shouldn't be there and I'm going to change it in a second

**Comment by Sunnnner** [comment]
> If possible I would like a test which shows that an url actually have expired or actually works, maybe mock/override whatever datetime.now() or similar method minio client uses to create an already invalid url. It's not super important but it would alert us if the minio python library silently changes it's behavior.
- I don't think I have the idea to test whether it is a time-limited URL minio. There is no official test about it, so I can have a try

**Comment by thomasf** [comment]
thanks for spending time on this. I implemented a max_age argument here https://github.com/py-pa/django-minio-storage/commit/5084b954ad0ba0afad340a8d1010ccd2e491a30c

**Comment by Sunnnner** [comment]
> thanks for spending time on this. I implemented a max_age argument here [5084b95](https://github.com/py-pa/django-minio-storage/commit/5084b954ad0ba0afad340a8d1010ccd2e491a30c)

thanks for the update, but I've rewritten the function

**Pull request closed without merging**
