### PR TITLE
Implemented a new way to handle policies due to recent minio API changes. All tests passed

### PR DESCRIPTION
**Pull request by VikVelev**
Added a _policy method, which returns a policy, created specifically for the bucket we need.
Rewrote the 'RetrieveTestsWithPublicBucket' test.

### CODE REVIEW

**Comment by VikVelev** [comment]
Seems like some of the Travis-CI tests that use earlier version of Minio API are failing and I think that's normal and not our fault. There are a few failed tests that are about code readability and formatting, which I will fix tomorrow if this isn't reviewed until then. 

I've personally tested the latest version with all my projects and everything is fine in terms of functionality, but I use docker a lot and installing manually a python module is quite a hassle. I would like this to be pushed to pip asap. Thank you in advance.

**Comment by thomasf** [comment]
Update minimum required minio version in setup.py and update tox.ini with that  versions as well

**Comment by VikVelev** [comment]
Should be ready to merge

**Comment by thomasf** [comment]
Thanks

**Comment by VikVelev** [comment]
How long does it typically take for the pypi package to update?

**Comment by thomasf** [comment]
Oh, thats not automatic.. I can make a new release and upload it.

**Comment by thomasf** [comment]
I'll try to do it this evening, otherwise I'll do it tomorrow.

**Comment by VikVelev** [comment]
Okay, please do. Thanks

**Comment by thomasf** [comment]
I published 0.2.1 now

**Comment by VikVelev** [comment]
Thanks

**Pull request merged**
