### PR TITLE
Update storage.py for Python 2.7 compatibility fix

### PR DESCRIPTION
**Pull request by Yurmusp**
Python 2.7 compatibility fix

### CODE REVIEW

**Comment by thomasf** [comment]
FIY: I quickly tried to add this and python 2.7 to the travis config before and that caused every test on py2 to fail.

**Comment by Yurmusp** [comment]
Do you have a link how it fails?

**Comment by thomasf** [comment]
I added a pull request to the other project.. it seems like there at least is a file encoding problem  https://github.com/py-pa/django-minio-storage/pull/9

**Comment by thomasf** [comment]
I guess could be because of the é in setup.py.. IIRC a regular file encoding header doesn't work for setup.py . I have other things on my priority list than supporting legacy python versions so I won't investigate this further right now,.

**Pull request closed without merging**
